# ▐▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▌
# ▐_____█████████___█████_____________████__████______________________██████___█████___________█████______▌#
# ▐____███░░░░░███_░░███_____________░░███_░░███_____________________░░██████_░░███___________░░███_______▌#
# ▐___░███____░░░__███████____██████__░███__░███___██████___████████__░███░███_░███___██████__███████_____▌#
# ▐___░░█████████_░░░███░____███░░███_░███__░███__░░░░░███_░░███░░███_░███░░███░███__███░░███░░░███░______▌#
# ▐____░░░░░░░░███__░███____░███████__░███__░███___███████__░███_░░░__░███_░░██████_░███████___░███_______▌#
# ▐____███____░███__░███_███░███░░░___░███__░███__███░░███__░███______░███__░░█████_░███░░░____░███_███___▌#
# ▐___░░█████████___░░█████_░░██████__█████_█████░░████████_█████_____█████__░░█████░░██████___░░█████____▌#
# ▐____░░░░░░░░░_____░░░░░___░░░░░░__░░░░░_░░░░░__░░░░░░░░_░░░░░_____░░░░░____░░░░░__░░░░░░_____░░░░░_____▌#
# ▐_______________________________________________________________________________________________________▌#
# ▐_______________________________________________________________________________________________________▌#
# ▐_______________________________________________________________________________________________________▌#
# ▐_________█████████_________________________██████___███________________________________________________▌#
# ▐________███░░░░░███_______________________███░░███_░░░_________________________________________________▌#
# ▐_______███_____░░░___██████__████████____░███_░░░__████___███████______________________________________▌#
# ▐______░███__________███░░███░░███░░███__███████___░░███__███░░███______________________________________▌#
# ▐______░███_________░███_░███_░███_░███_░░░███░_____░███_░███_░███______________________________________▌#
# ▐______░░███_____███░███_░███_░███_░███___░███______░███_░███_░███______________________________________▌#
# ▐_______░░█████████_░░██████__████_█████__█████_____█████░░███████______________________________________▌#
# ▐________░░░░░░░░░___░░░░░░__░░░░_░░░░░__░░░░░_____░░░░░__░░░░░███______________________________________▌#
# ▐_________________________________________________________███_░███______________________________________▌#
# ▐________________________________________________________░░██████_______________________________________▌#
# ▐_________________________________________________________░░░░░░________________________________________▌#
# ▐▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▌#

language: en

#Timer Configs
minMinutes: 30
maxMinutes: 40